---
# Title: CrowdSec Agent
#
# Author: Bitfinity-NL / L. Rutten
# Owner: Bitfinity-NL / IT Operations
#
# File: tasks/main.yml
#
# Description:
#   This role contains the configurations 
#   steps for installing CrowdSec agent.
#

- name: "Install CrowdSec on Ubuntu or Debian systems"
  include_tasks: ubuntu-debian.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
